### ISSUE TITLE
Ghost button in Stopwatch

### ISSUE THREAD

**Issue by RaneLafraze** [BroManSalaam/Sportwatch_app#2]
Ghost button (functionality unknown) in Stopwatch page
![spotwatch](https://user-images.githubusercontent.com/12915796/50652338-3efdca00-0f54-11e9-9ad7-4ad23994455a.png)

**Comment by BroManSalaam** [comment]
Yup, I'm painfully aware lol, it looks even more noticable on iOS, thanks
for the reminder :(

**Comment by RaneLafraze** [comment]
Sorry, I didn't mean it like that, I was just putting it here as a sort of TODO / reminder.

**Comment by RaneLafraze** [comment]
Fixed in Pull Request #4.
